# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mads.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mads.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmads.proto\"!\n\x06Object\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03URI\x18\x02 \x01(\t\"&\n\x17UserCreateObjectRequest\x12\x0b\n\x03URI\x18\x01 \x01(\t\"3\n\x18UserCreateObjectResponse\x12\x17\n\x06object\x18\x01 \x01(\x0b\x32\x07.Object2W\n\x0cmads_service\x12G\n\x10userCreateObject\x12\x18.UserCreateObjectRequest\x1a\x19.UserCreateObjectResponseb\x06proto3'
)




_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Object.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='URI', full_name='Object.URI', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=47,
)


_USERCREATEOBJECTREQUEST = _descriptor.Descriptor(
  name='UserCreateObjectRequest',
  full_name='UserCreateObjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='URI', full_name='UserCreateObjectRequest.URI', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=87,
)


_USERCREATEOBJECTRESPONSE = _descriptor.Descriptor(
  name='UserCreateObjectResponse',
  full_name='UserCreateObjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='object', full_name='UserCreateObjectResponse.object', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=140,
)

_USERCREATEOBJECTRESPONSE.fields_by_name['object'].message_type = _OBJECT
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['UserCreateObjectRequest'] = _USERCREATEOBJECTREQUEST
DESCRIPTOR.message_types_by_name['UserCreateObjectResponse'] = _USERCREATEOBJECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'mads_pb2'
  # @@protoc_insertion_point(class_scope:Object)
  })
_sym_db.RegisterMessage(Object)

UserCreateObjectRequest = _reflection.GeneratedProtocolMessageType('UserCreateObjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERCREATEOBJECTREQUEST,
  '__module__' : 'mads_pb2'
  # @@protoc_insertion_point(class_scope:UserCreateObjectRequest)
  })
_sym_db.RegisterMessage(UserCreateObjectRequest)

UserCreateObjectResponse = _reflection.GeneratedProtocolMessageType('UserCreateObjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERCREATEOBJECTRESPONSE,
  '__module__' : 'mads_pb2'
  # @@protoc_insertion_point(class_scope:UserCreateObjectResponse)
  })
_sym_db.RegisterMessage(UserCreateObjectResponse)



_MADS_SERVICE = _descriptor.ServiceDescriptor(
  name='mads_service',
  full_name='mads_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=142,
  serialized_end=229,
  methods=[
  _descriptor.MethodDescriptor(
    name='userCreateObject',
    full_name='mads_service.userCreateObject',
    index=0,
    containing_service=None,
    input_type=_USERCREATEOBJECTREQUEST,
    output_type=_USERCREATEOBJECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MADS_SERVICE)

DESCRIPTOR.services_by_name['mads_service'] = _MADS_SERVICE

# @@protoc_insertion_point(module_scope)
