# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mads_pb2 as mads__pb2


class mads_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.userCreateObject = channel.unary_unary(
                '/mads_service/userCreateObject',
                request_serializer=mads__pb2.UserCreateObjectRequest.SerializeToString,
                response_deserializer=mads__pb2.UserCreateObjectResponse.FromString,
                )


class mads_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def userCreateObject(self, request, context):
        """User creates object and gets a response:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_mads_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'userCreateObject': grpc.unary_unary_rpc_method_handler(
                    servicer.userCreateObject,
                    request_deserializer=mads__pb2.UserCreateObjectRequest.FromString,
                    response_serializer=mads__pb2.UserCreateObjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mads_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class mads_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def userCreateObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mads_service/userCreateObject',
            mads__pb2.UserCreateObjectRequest.SerializeToString,
            mads__pb2.UserCreateObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
