# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mads_pb2 as mads__pb2


class mads_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.userCreateObject = channel.unary_unary(
                '/mads_service/userCreateObject',
                request_serializer=mads__pb2.UserCreateObjectRequest.SerializeToString,
                response_deserializer=mads__pb2.UserCreateObjectResponse.FromString,
                )
        self.pluginCreateDescription = channel.unary_unary(
                '/mads_service/pluginCreateDescription',
                request_serializer=mads__pb2.PluginCreateDescriptionRequest.SerializeToString,
                response_deserializer=mads__pb2.PluginCreateDescriptionResponse.FromString,
                )
        self.pluginTranslateDescription = channel.unary_unary(
                '/mads_service/pluginTranslateDescription',
                request_serializer=mads__pb2.PluginTranslateDescriptionRequest.SerializeToString,
                response_deserializer=mads__pb2.PluginTranslateDescriptionResponse.FromString,
                )
        self.pluginExtractExifData = channel.unary_unary(
                '/mads_service/pluginExtractExifData',
                request_serializer=mads__pb2.PluginExtractExifDataRequest.SerializeToString,
                response_deserializer=mads__pb2.PluginExtractExifDataResponse.FromString,
                )
        self.pluginSupplyGeodata = channel.unary_unary(
                '/mads_service/pluginSupplyGeodata',
                request_serializer=mads__pb2.PluginSupplyGeodataRequest.SerializeToString,
                response_deserializer=mads__pb2.PluginSupplyGeodataResponse.FromString,
                )
        self.userRequestsTagsForObject = channel.unary_stream(
                '/mads_service/userRequestsTagsForObject',
                request_serializer=mads__pb2.UserRequestsTagsForObjectRequest.SerializeToString,
                response_deserializer=mads__pb2.UserRequestsTagsForObjectResponse.FromString,
                )


class mads_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def userCreateObject(self, request, context):
        """User creates object and gets a response:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pluginCreateDescription(self, request, context):
        """Create automatic description in english:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pluginTranslateDescription(self, request, context):
        """Translate the automatically created description into user language
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pluginExtractExifData(self, request, context):
        """Extract EXIF data from a new object:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pluginSupplyGeodata(self, request, context):
        """Supply with geodata given EXIF data:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def userRequestsTagsForObject(self, request, context):
        """User wants all tags for an object:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_mads_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'userCreateObject': grpc.unary_unary_rpc_method_handler(
                    servicer.userCreateObject,
                    request_deserializer=mads__pb2.UserCreateObjectRequest.FromString,
                    response_serializer=mads__pb2.UserCreateObjectResponse.SerializeToString,
            ),
            'pluginCreateDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.pluginCreateDescription,
                    request_deserializer=mads__pb2.PluginCreateDescriptionRequest.FromString,
                    response_serializer=mads__pb2.PluginCreateDescriptionResponse.SerializeToString,
            ),
            'pluginTranslateDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.pluginTranslateDescription,
                    request_deserializer=mads__pb2.PluginTranslateDescriptionRequest.FromString,
                    response_serializer=mads__pb2.PluginTranslateDescriptionResponse.SerializeToString,
            ),
            'pluginExtractExifData': grpc.unary_unary_rpc_method_handler(
                    servicer.pluginExtractExifData,
                    request_deserializer=mads__pb2.PluginExtractExifDataRequest.FromString,
                    response_serializer=mads__pb2.PluginExtractExifDataResponse.SerializeToString,
            ),
            'pluginSupplyGeodata': grpc.unary_unary_rpc_method_handler(
                    servicer.pluginSupplyGeodata,
                    request_deserializer=mads__pb2.PluginSupplyGeodataRequest.FromString,
                    response_serializer=mads__pb2.PluginSupplyGeodataResponse.SerializeToString,
            ),
            'userRequestsTagsForObject': grpc.unary_stream_rpc_method_handler(
                    servicer.userRequestsTagsForObject,
                    request_deserializer=mads__pb2.UserRequestsTagsForObjectRequest.FromString,
                    response_serializer=mads__pb2.UserRequestsTagsForObjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mads_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class mads_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def userCreateObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mads_service/userCreateObject',
            mads__pb2.UserCreateObjectRequest.SerializeToString,
            mads__pb2.UserCreateObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pluginCreateDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mads_service/pluginCreateDescription',
            mads__pb2.PluginCreateDescriptionRequest.SerializeToString,
            mads__pb2.PluginCreateDescriptionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pluginTranslateDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mads_service/pluginTranslateDescription',
            mads__pb2.PluginTranslateDescriptionRequest.SerializeToString,
            mads__pb2.PluginTranslateDescriptionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pluginExtractExifData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mads_service/pluginExtractExifData',
            mads__pb2.PluginExtractExifDataRequest.SerializeToString,
            mads__pb2.PluginExtractExifDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pluginSupplyGeodata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mads_service/pluginSupplyGeodata',
            mads__pb2.PluginSupplyGeodataRequest.SerializeToString,
            mads__pb2.PluginSupplyGeodataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def userRequestsTagsForObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mads_service/userRequestsTagsForObject',
            mads__pb2.UserRequestsTagsForObjectRequest.SerializeToString,
            mads__pb2.UserRequestsTagsForObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
